PREFIX yaco: <https://www.irit.fr/recherches/MELODI/ontologies/cinema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?actor (?curYear-?birthYear AS ?age)
WHERE {
  ?actor rdf:type yaco:Actor;
    yaco:birthYear ?birthYear.
  BIND(year(now()) as ?curYear)

}
