PREFIX yaco: <https://www.irit.fr/recherches/MELODI/ontologies/cinema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?name
WHERE {
  ?actor rdf:type yaco:Actor;
    rdfs:label ?name;
    yaco:playsRole ?role.
} GROUP BY ?actor
HAVING (COUNT(?role) > 2)
