PREFIX yaco: <https://www.irit.fr/recherches/MELODI/ontologies/cinema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?movie ?year
WHERE {
  ?movie rdf:type yaco:Movie.
  OPTIONAL {
    ?movie yaco:releaseYear ?year
    FILTER(?year = 1997)
  }
}
